### ISSUE TITLE
Null pointer if promotion plugin missing

### ISSUE THREAD

**Issue by devshorts** [paradoxical-io/francois#1]
```
ERROR [2016-01-08 21:38:28,054] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 18416df48a6be634
! java.lang.NullPointerException: null
! at io.paradoxical.francois.jenkins.PromotionTemplateLoader.getJobPromotions(PromotionTemplateLoader.java:37) ~[francois-core-1.0-SNAPSHOT-r6fcf9d9_dev.jar:na]
! at io.paradoxical.francois.jenkins.PromotionTemplateLoader.getPromotionTemplates(PromotionTemplateLoader.java:24) ~[francois-core-1.0-SNAPSHOT-r6fcf9d9_dev.jar:na]
! at io.paradoxical.francois.jenkins.TemplateManager.getAllParameters(TemplateManager.java:46) ~[francois-core-1.0-SNAPSHOT-r6fcf9d9_dev.jar:na]
! at io.paradoxical.francois.resources.api.v1.FrancoisResource.getTemplateParameters(FrancoisResource.java:72) ~[francois-core-1.0-SNAPSHOT-r6fcf9d9_dev.jar:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66-internal]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66-internal]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66-internal]
! at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66-internal]
```

**Comment by devshorts** [comment]
Also fails if the job doesn't have a promotion step defined.

**Comment by jakeswenson** [comment]
Problem solved by you! thanks
